language: node_js
addons:
  chrome: stable
node_js:
  - "11"
before_script:
  - npm install -g chromedriver
  - npm install -g selenium-side-runner
script:
  - selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" STARHOTEL_reservation.side
